# Generated by Django 4.0.4 on 2022-05-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BursaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=99, verbose_name='Адрес')),
                ('description', models.CharField(default=None, max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=30, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=99, verbose_name='ФИО')),
                ('course', models.IntegerField(default=None, verbose_name='Курс')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_students.facultymodel', verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=10, verbose_name='Номер Комнаты')),
                ('students', models.ManyToManyField(to='app_students.studentsmodel', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionBursaRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bursa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_students.bursamodel', verbose_name='Id общежития')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_students.roommodel', verbose_name='Id общежития')),
            ],
        ),
    ]
