# Generated by Django 4.0.4 on 2022-05-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_students.facultymodel', verbose_name='Специальность'),
        ),
    ]
